services:
  ml_service:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env                # загружает все переменные из .env (секреты, TTL и т.д.)
    volumes:
      - ./diabetes_model.onnx:/app/diabetes_model.onnx   # монтируем модель (если не встроена в образ)
    restart: unless-stopped